DEFINE
MEASURE 'Ranking Table' [Total2]= FORMAT( SUM('Ranking Table'[Total Line Amount])*25,"Currency")

EVALUATE
(
SUMMARIZE('Ranking Table', 'Ranking Table'[State], 'Ranking Table'[ProductName],
'Ranking Table'[Rank], 
"Total Line Amount", SUM('Ranking Table'[Total Line Amount]),
"Total Ranking Table2", 'Ranking Table' [total2]

)
)

EVALUATE
(
'Ranking Table'

)	ORDER BY 'Ranking Table'[Rank] asc